source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ELMEasyLocationManager_Example', :exclusive => true do
  pod "ELMEasyLocationManager", :path => "../"
end

target 'ELMEasyLocationManager_Tests', :exclusive => true do
  pod "ELMEasyLocationManager", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
